### ISSUE TITLE
Twitterオブジェクトから直接のxAuthはサポートしない方針ですか？

### ISSUE THREAD

**Issue by marihachi** [syuilo/Twitch2#4]
- Authorize.GetAccessTokenFromXAuth()でTwitterオブジェクトを得る方法
- Twitter.OauthAccessToken(string, string)でjsonを得てTwitterオブジェクトを手動で生成する方法
  主にこの２つの方法でxAuthは使えますが、TwitterオブジェクトからxAuthをする為の直接的なサポートの予定はあるんでしょうか

**Comment by syuilo** [comment]
検討なう

**Comment by syuilo** [comment]
Implemented

**Comment by marihachi** [comment]
ありがとう
